import os
import json


def save_json(data, filename: str):
    """ Saves parsed receipt data as JSON """
    output_folder = os.path.join("output", "autogenerated")
    os.makedirs(output_folder, exist_ok=True)

    file_path = os.path.join(output_folder, filename)
    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"Results saved to: {file_path}")
