import json

# Load the JSON data from the file
with open('output/autogenerated/parsed_receipts.json', 'r') as file:
    data = json.load(file)

# Define the target names to search for
target_names = ["1 X", "2 X", "3 X", "4 X", "5 X"]

# Iterate through the receipts and search for the target names
for receipt in data:
    for item in receipt['items']:
        if item['name'] in target_names:
            print(f"Found '{item['name']}' in file: {receipt['file']}")